ai:
  model: "deepseek/deepseek-chat"
  api_base: "https://api.deepseek.com"
  api_key: "AI_API_KEY"

push:
  telegram:
    enabled: true
    token: "TELEGRAM_TOKEN"
    chat_id: "1784347650"

language: "zh_CN" 
